config/routes.rb
Rails.application.routes.draw do
  resources :roles
  resources :productos
  devise_for :users, controllers: {
    sessions: 'devise/sessions'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "main#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/producto.rb
class Producto < ApplicationRecord
  has_one_attached :photo
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :role_users
  has_many :users, through: :role_users
end

app/models/role_user.rb
class RoleUser < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :role_users
  has_many :roles, through: :role_users

  def admin?
    roles.exists?(name: "admin")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization

  # Verify that policies are used for all actions in controllers
  #after_action :verify_authorized, except: :index
  #after_action :verify_policy_scoped, only: :index
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
  end

  def home
    @productos = Producto.all
    authorize :producto
  end
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: %i[show edit update destroy]

  def index
    @productos = Producto.all
  end

  def show
    authorize @producto
  end

  def new
    @producto = Producto.new
    authorize @producto
  end

  def edit
    authorize @producto
  end

  def create
    @producto = Producto.new(producto_params)
    authorize @producto

    respond_to do |format|
      if @producto.save
        format.html { redirect_to producto_url(@producto), notice: "Producto was successfully created." }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @producto

    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to producto_url(@producto), notice: "Producto was successfully updated." }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @producto
    @producto.destroy

    respond_to do |format|
      format.html { redirect_to productos_url, notice: "Producto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_producto
    @producto = Producto.find(params[:id])
  end

  def producto_params
    params.require(:producto).permit(:name, :description, :photo, :price)
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: %i[ show edit update destroy ]

  # GET /roles or /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1 or /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles or /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to role_url(@role), notice: "Role was successfully created." }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1 or /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to role_url(@role), notice: "Role was successfully updated." }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1 or /roles/1.json
  def destroy
    @role.destroy

    respond_to do |format|
      format.html { redirect_to roles_url, notice: "Role was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def role_params
      params.require(:role).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? && policy(Producto.new).create? %>
          <li class="nav-item">
            <%= link_to "Crear producto", new_producto_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      <ul class="navbar-nav">
        <% if current_user %>
          <li class="nav-item">
            <%= link_to "Edit Account", edit_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-small btn-primary mx-2", style: "background-color: none; color: black;" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link"  %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class: "nav-link"  %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaranjaGym</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <% if flash[:notice] %>
    <div class="alert alert-success alert-dismissible fade show mb-0" role="alert">
      <%= flash[:notice] %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
  <% if flash[:alert] %>
    <div class="alert alert-warning alert-dismissible fade show mb-0" role="alert">
      <%= flash[:alert] %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
  <div class="container-fluid">
    <%= yield %>
  </div>
  </body>
</html>

app/views/main/home.html.erb
<!-- Header -->
<header class="bg-dark py-5">
  <div class="container px-4 px-lg-5 my-5">
    <div class="text-center text-white">
      <h1 class="display-4 fw-bolder">NARNAJA GYM</h1>
      <p class="lead fw-normal text-white-50 mb-0">Compra tu membresia y productos fitness al mejor precio</p>
    </div>
  </div>
</header>

<!-- Section -->
<section class="py-5">
  <div class="container px-4 px-lg-5 mt-5">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
      <% @productos.each do |producto| %>
        <div class="col mb-5">
          <div class="card h-100">
            <!-- Product image -->
            <%= image_tag producto.photo, class: "card-img-top product-image" if producto.photo.attached? %>

            <!-- Product details -->
            <div class="card-body p-4">
              <div class="text-center">
                <!-- Product name -->
                <h5 class="fw-bolder"><%= producto.name %></h5>
                <!-- Product price -->
                <%= number_to_currency(producto.price) %>
              </div>
            </div>

            <!-- Product actions -->
            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
              <div class="text-center">
                <% if policy(producto).show? && !current_user&.admin? %>
                  <%= link_to "Ver mas detalle", producto, class: "btn btn-outline-dark mt-auto", style: "background-color: #212529; color: #fff;" %>
                <% elsif current_user&.admin? %>
                  <%= link_to "Comprar", producto, class: "btn btn-outline-dark mt-auto", style: "background-color: #212529; color: #fff;" %>
                  <%= link_to "Editar", edit_producto_path(producto), class: "btn btn-outline-dark mt-auto", style: "background-color: #212529; color: #fff;" %>
                  <%= button_to "Eliminar", producto, method: :delete, class: "btn btn-outline-dark mt-auto", style: "background-color: #212529; color: #fff;" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

<style>
    .product-image {
        width: 100%;
        height: 300px; /* Ajusta la altura deseada */
        object-fit: cover;
    }
</style>

app/views/productos/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <%= form_with(model: producto, local: true, html: {multipart: true}) do |form| %>
        <% if producto.errors.any? %>
          <div class="alert alert-danger">
            <h2><%= pluralize(producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

            <ul>
              <% producto.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="mb-3">
          <%= form.label :name, class: "form-label" %>
          <%= form.text_field :name, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= form.label :description, class: "form-label" %>
          <%= form.text_area :description, class: "form-control", rows: 5 %>
        </div>

        <div class="mb-3">
          <%= form.label :photo, class: "form-label" %>
          <%= form.file_field :photo, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= form.label :price, class: "form-label" %>
          <%= form.text_field :price, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= form.submit "Save", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/productos/_producto.html.erb
<div id="<%= dom_id producto %>">
  <%= image_tag producto.photo %>
  <p>
    <strong>Name:</strong>
    <%= producto.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= producto.description %>
  </p>
  <p>
    <strong>Price:</strong>
    <%= producto.price %>
  </p>

</div>

app/views/productos/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-10">
      <h1 class="row justify-content-center">Editar producto</h1>

      <%= render "form", producto: @producto %>

      <br>

      <div class="text-center">
        <%= link_to "Mostrar este producto", @producto, class: "btn btn-primary me-2" %> |
        <%= link_to "Volver a productos", root_path, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>

app/views/productos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Productos</h1>

<div id="productos">
  <% @productos.each do |producto| %>
    <%= render partial: 'producto', locals: { producto: producto } %>
    <p>
      <%= link_to "Show this producto", producto %>
    </p>
  <% end %>
</div>

<%= link_to "New producto", new_producto_path %>

app/views/productos/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-10">
      <h1 class="row justify-content-center">Crear producto</h1>

      <%= render "form", producto: @producto %>

      <br>

      <div class="text-center">
        <%= link_to "Volver a productos", root_path, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>

app/views/productos/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <p class="text-success"><%= notice %></p>

      <div class="text-center">
        <%= image_tag @producto.photo, class: "img-fluid rounded" if @producto.photo.attached? %>
      </div>

      <div id="<%= dom_id @producto %>" class="mt-4">
        <h5 class="mb-1">
          <strong>Name:</strong>
        </h5>
        <p class="text-muted"><%= @producto.name %></p>

        <h5 class="mb-1">
          <strong>Description:</strong>
        </h5>
        <p class="text-muted"><%= @producto.description %></p>

        <h5 class="mb-1">
          <strong>Price:</strong>
        </h5>
        <p class="text-muted"><%= @producto.price %></p>
      </div>

      <div class="mt-4">
        <div class="mb-3">
          <% if policy(@producto).update? %>
            <%= link_to "Editar producto", edit_producto_path(@producto), class: "btn btn-primary me-2" %>
          <% end %>
          <% if policy(@producto).destroy? %>
            <%= button_to "Eliminar producto", @producto, method: :delete, data: { confirm: "¿Estás seguro de eliminar este producto?" }, class: "btn btn-danger me-2" %>
          <% end %>
        </div>

        <div class="mb-3">
          <% if policy(@producto).show? %>
            <%= button_to "Comprar", @producto, method: :post, data: { confirm: "¿Comprar este producto?" }, class: "btn btn-success", onclick: "showSuccessMessage()" %>
          <% end %>
          <%= link_to "Volver a productos", root_path, class: "btn btn-secondary" %>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
    function showSuccessMessage() {
        var successMessage = document.createElement('p');
        successMessage.innerText = 'Comprado con éxito!';
        successMessage.style.color = 'green';
        document.getElementById('<%= dom_id @producto %>').insertBefore(successMessage, document.getElementById('<%= dom_id @producto %>').firstChild);
    }
</script>

app/views/roles/_form.html.erb
<%= form_with(model: role) do |form| %>
  <% if role.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
        <% role.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/roles/_role.html.erb
<div id="<%= dom_id role %>">
  <p>
    <strong>Name:</strong>
    <%= role.name %>
  </p>

</div>

app/views/roles/edit.html.erb
<h1>Editing role</h1>

<%= render "form", role: @role %>

<br>

<div>
  <%= link_to "Show this role", @role %> |
  <%= link_to "Back to roles", roles_path %>
</div>

app/views/roles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Roles</h1>

<div id="roles">
  <% @roles.each do |role| %>
    <%= render role %>
    <p>
      <%= link_to "Show this role", role %>
    </p>
  <% end %>
</div>

<%= link_to "New role", new_role_path %>

app/views/roles/new.html.erb
<h1>New role</h1>

<%= render "form", role: @role %>

<br>

<div>
  <%= link_to "Back to roles", roles_path %>
</div>

app/views/roles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @role %>

<div>
  <%= link_to "Edit this role", edit_role_path(@role) %> |
  <%= link_to "Back to roles", roles_path %>

  <%= button_to "Destroy this role", @role, method: :delete %>
</div>